### ISSUE TITLE
Colorlight Firmware 13.17  not compatible with 7.5.x

### ISSUE THREAD

**Issue by derwin12** [FalconChristmas/fpp#1849]
From zoom. .. Travis had to have the guy downgrade back to 11.04 and it worked without issues. Someone noted that there is a more recent version.
Ledvision 8.5 was used. This was with a Pi4 and builtin eth0. Panels were P2. Not sure if this is something to fix or perhaps just to document and close the ticket. (P2-1515-128x64-32s)

**Comment by mjunek** [comment]
To add to this, I had a very similar issue just now.
FPP 7.5-5-gda02180d (Latest update as at 10 June)
Colorlight 8.2 card with 13.39 firmware. 
Pi 4 CM4 on a carrier board, built-in eth0.
Panels are 48x48 P6.67s, in 3x2 array
LEDVision 8.8

No output from FPP. Panel would flash when enabling output, but no pixels illuminating.
LEDVision pie graph setup output would produce flicker and was also a bit lagged.

Downgraded to 11.04 firmware after reading the above note, issue disappeared. FPP could talk fine, and LEDVIsion lag disappeared.

**Comment by darylc** [comment]
Added warning to UI in https://github.com/FalconChristmas/fpp/commit/306f0f6065cd25a32441ee4492576ace61ab799d

**Comment by mjunek** [comment]
I've popped a copy of the 5A v11.04 firmware on my site in case it's required by anyone who encounters this issue and wishes to downgrade: https://www.mortonlights.com/files/ColorLight_5A_v11.04.fw

**Comment by Indigogyre** [comment]
I'm also having an issue using the latest firmware 13.39. The type of panel does not seem to matter as long as the firmware is higher then 11.04 it doesn't seem to work. 

Working Colorlight card with my P5 panels upgrade it to 13.39 and FPP is no longer able to use it. Downgrade to 11.04 and it works fine with no other changes.

My issue is that I am trying to configure P4 80x40-20s panels and they seem to need the higher firmware version to work properly. When using the 11.04 firmware the panels have refresh issues which are not present when configuring with the 13.39 version.

FPP 7.5 Updated today.
Colorlight 8.2 card with 13.39 firmware. (Tested multiple cards)
Pi 4 CM4 on a carrier board, built-in eth0.

**Comment by darylc** [comment]
We need a volunteer to do some detailed packet tracing and reverse engineering and submit an enhancement for this.  The developer who wrote the initial colorlight code is currently not active in FPP development.

**Comment by JonB256** [comment]
Is this related to the error message I'm seeing on my RasPi 4 and latest FPP v8.1 (master) where it tells me that eth0 is NOT capable of Gigabit connection to a ColorLight card? (it isn't currently connected to a powered ColorLight card, if that makes a difference)

![image](https://github.com/user-attachments/assets/458997b4-5388-42da-8f15-04818185fd65)

**Comment by cybercop23** [comment]
Check the cable and make sure all 4 pairs are connected. 1Gbps needs all 4 pairs. Best if you have an ethernet cable tester.

**Comment by ebuechner** [comment]
It looks like 5A 3.80 is not compatible.
It will come up with communication errors like JohnB256 has.

**Comment by ebuechner** [comment]
I ran into the "abnormal conditions" warning and after a lot of trial and error it came down to running the 5A 3.80 firmware.
After changing the firmware I haven't had the problem come back yet. I'll update if anything else comes up.
I have to note that when I was having problems and it came up with the error it would stop outputting to the colorlight card and refused to reset until you do a full reboot. Restarting the FPPD would not clear it.
All of these problems came up after running 8.0.

**Comment by bobreese** [comment]
> Is this related to the error message I'm seeing on my RasPi 4 and latest FPP v8.1 (master) where it tells me that eth0 is NOT capable of Gigabit connection to a ColorLight card? (it isn't currently connected to a powered ColorLight card, if that makes a difference)
> 
> ![image](https://private-user-images.githubusercontent.com/5251235/354636157-458997b4-5388-42da-8f15-04818185fd65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjQ2MDksIm5iZiI6MTcyNTk2NDMwOSwicGF0aCI6Ii81MjUxMjM1LzM1NDYzNjE1Ny00NTg5OTdiNC01Mzg4LTQyZGEtOGYxNS0wNDgxODE4NWZkNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTAzMTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZlOTY5YTljZmVkMjMwNjg2OWFjYWFjZWNlNjY0MTk2NmYwNGJkZjI0ODVmZmYxZjFmMDRjZjE5MGYxZDk3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._pNCoCHKCDGDocr2yBNXFn1skLaxV43eHBm0i60oPpA)

The connection speed has been corrected  (https://github.com/FalconChristmas/fpp/pull/1955)
The second error will remain until the colorlight card is connected and powered on.

**Comment by Indigogyre** [comment]
I took a couple of Wireshark packet captures they are a little over 12ish seconds. I let the simple LEDVision output play during the capture and at about the 10s mark i moved my cursor on the normal screen display to possibly generate different packets.

5A75B 11v09:
Indoor P5 panel to work with receiver 
5A-75B v8.2 with the 11.09 firmware

5A75B 13v39:
Indoor P5 panel to work with receiver 
5A-75B v8.2 with the 13.39 firmware

This is a start, let me know if there are other captures to work on.
[Packet Captures 01.zip](https://github.com/user-attachments/files/16955717/Packet.Captures.01.zip)

**Comment by mjunek** [comment]
Thanks @Indigogyre - I do see a difference between those pcaps and what the FPP code is generating. I will run some tests with some code modifications against my panels in the coming week and if I find a positive change in behaviour I'll submit a PR for inclusion.

**Comment by AlecDusheck** [comment]
I really appreciate yall looking into this. I'm curious if anyone has made any progress so far in spotting the differences in the new protocol. I'm awaiting receiving a 5A-75B that will probably arrive with the 13.39 firmware :/

**Comment by AlecDusheck** [comment]
Also, if it helps, I've created a custom ColorLight Wireshark plugin, available here: https://github.com/JoinRiata/Wireshark-Scripts/blob/main/colorlight.lua

This is very much untested, but hopefully it can make debugging a little easier :)

![image](https://github.com/user-attachments/assets/e092b635-c30e-47e1-a292-bdda0fd3fb71)

**Comment by mjunek** [comment]
I did have some success last night getting an image out of the newer Colorlight firmware with some changes in FPP. It was flickering like mad, more work needs to be done, but I think I am on the right track.

Definitely gonna take alook at your plugin @AlecDusheck  - that looks fantastically useful.

**Comment by mjunek** [comment]
This now appears to be a timing issue with the packets. It's likely that the new firmware is pushing the FPGA to the limits on the receiver card, and FPP is too efficient at getting the packets on the wire. 
@Indigogyre or others; does anyone have a Colorlight Sender card? I'd love to see a pcap of the data and timing from one of those for comparisons.

**Comment by Indigogyre** [comment]
> This now appears to be a timing issue with the packets. It's likely that the new firmware is pushing the FPGA to the limits on the receiver card, and FPP is too efficient at getting the packets on the wire. @Indigogyre or others; does anyone have a Colorlight Sender card? I'd love to see a pcap of the data and timing from one of those for comparisons.

I do have a S2 sender card and can do a capture of the data out. Let me work on that and I will post the capture when it is available.

**Comment by Indigogyre** [comment]
@mjunek, let me know if this one is useful or not, it's the first time I tried to capture an incoming form the sender card. If it is wrong I can redo the capture.

[S2 Sender.zip](https://github.com/user-attachments/files/17266685/S2.Sender.zip)

**Comment by mjunek** [comment]
Thanks @Indigogyre that's a valid capture, and also shows yet another lot of data coming in. I'll see if I make more progress replicating this.

**Comment by patdelaney** [comment]
On behalf of the FPP team, I just want to say thank you for all the work you are putting into this to help figure this out. At times we just don't have the bandwidth.

**Comment by AlecDusheck** [comment]
Just checking in on this issue! @mjunek would you mind explaining what changes you made to get something to display :)

**Comment by mjunek** [comment]
Hi @AlecDusheck - It required numerous changes to the headers and duplication of packets.

I aim to pick this back up once my display is operational for the season, unfortunately I've been a little pre-occupied with that lately to spend time on the issue.

As an update - however - I have a sender card to now test with, and that is working perfectly. My first goal will be to replicate what it's sending and hope for the best.

I also note that LEDVision v9 strips out the ability to configure receiver cards directly without a sender card. LEDVision v8 has the lag issues direct to the v13 receiver cards too - this is a concern to me as it may be sending from a computer may not longer be reliable or possible.

**Comment by jkriegshauser** [comment]
I'm running into the same issue as @JonB256 reported above:
![image](https://github.com/user-attachments/assets/f72e134c-1a85-4e93-a49f-53240107199b)

My logs just show:

> [ChannelOut] /opt/fpp/src/channeloutput/ColorLight-5a-75.cpp:287: Error ColorLight: Configured interface eth1 does not have link No such file or directory

If I power-cycle the whole P5 panel/colorlight/RPi sometimes it "works." After about 3 power-cycles tonight it finally started displaying stuff but cut off the bottom ~10 rows or so.

How do we check which firmware the ColorLight is on?

**Comment by AlecDusheck** [comment]
@jkriegshauser use [LEDUpgrade](https://en.colorlightinside.com/service/download/?cat=959)

Its easy to downgrade if you need

**Comment by napdsp** [comment]
I have the same problem after upgraded to FPP 8.4.1 from 7.5.
I solved the problem by
1. Power cycle the Pi
2. It will report the problem still
3. Immediately reboot from the web UI

Once rebooted, the problem goes away for me. I hope this helps some of you.

**Comment by jkriegshauser** [comment]
My Colorlight was never on the 13.xx firmware. I downgraded my FPP from 8.3 to 7.4 and it's working perfectly now. Seems like something broke between those versions.

**Comment by cpinkham** [comment]
The capture above from the S2 card shows that the sender card is sending a different sync or header packet to the receiver ahead of each frame of data.  The older cards use a packet with 0x0AFF in it between each frame and the S2 capture shows only a 0x0100 type packet with what appears to be a 8-bit frame counter in the 15th byte.  This value loops from 0 to 255 then resets back to 0.  This could be why you see flicker, because FPP isn't sending this packet so the receiver has to time out before flushing the data to the outputs.

I looked at the other captures in the other zip and see the computer sending a 0x0107 type packet at the start instead of the 0x0101 type packet that FPP sends at startup.  The other difference I see in these packet captures is byte 21 is 0x88 instead of the 0x80 that FPP is sending.  My only Windows computer in my office died years ago so I will dig up a Windows laptop or something to try to upgrade the firmware on one of my receivers and then I could try some changes to FPP.

@mjunek do you have any other info to report since your last test?

**Comment by mjunek** [comment]
@cpinkham The 0x0AFF packet is the panel brightness setting. By manipulating this value from 0x0A00 to 0xAFF you can adjust the brightness of the panel, without modifying the actual data stream. I've been looking at whether this is consistent across firmware to see if it's worth putting into the front end. 
If it's consistent, then I think it's a great addition as then it'll use the Colorlight gamma curves etc.

On v13 firmware, the 0x0107 type packet was one thing that was needed to get it working, along with the 0x88 frame as you notice.
However - one thing I noticed that LEDVision appeared to be doubling the packets. When testing with this from FPP, I could get an output, although insanely lagged (much like LEDVision). Replicating the exact data in the Sender Card packet did not produce an output, it's likely packet timing related however.

**Comment by cpinkham** [comment]
I have a pair of ColorLight cards configured identical and setup in a chain with one using older firmware and one using 13.x so I can easily test FPP changes against two different firmware versions at the same time.

I have reworked part of the code to make it more prominent that it is a single-byte packet type (0x01, 0x0A, 0x55) and am updating the docs in the comments some.  I have a patch which allows the 13.x firmware to work by duplicating the 0x01 packet, but the same exact code doesn't work on the older firmware.  I think that the 0x01 packet is a sync packet and am wondering if we are not giving enough delay between the 0x01 and the 0x55 data packets.  I'm going to do some testing with that.  The 0x0A brightness packet doesn't seem to be needed since brightness control appears to work fine with new/old firmware when set in the 0x01 packet.  Currently we send the 0x01 followed by the 0x55 packets all in one shot using sendmmsg(), so I'm going to experiment some with reordering the 0x01 after the 0x55.  If that works, I'll look at moving the 0x55 into our PrepData() call and just send the 0x01 in SendData().

My current code also allows me to test with 0x01 packets with the next byte being 0x00 and byte offset 23 being 0x00 as sent by the S2 sender shown in the capture posted to this ticket.   The 13.x receiver works both ways, so I don't think this is a PC vs S2 issue, I think it is something to do with the 0x01 packet timing.  I have tried with/without the 0x0A brightness packet as well as doubling the 0x0A packet and/or all the 0x55 data packets and it appears the only one that needs doubling on the 13.x firmware is the 0x01 packet.  This could be due to timing though, so that is something else I plan to test.  I'm also wondering whether the flicker with 13.x firmware is related to this double-0x01 packet and the timing.

**Comment by cpinkham** [comment]
I have been playing with this more.  I have code which can drive both old and new firmware versions, but the old firmware flickers some when sending the two 0x01 packets.  I have been testing with 3.x and 13.x firmware, and need to test with a third card I have.  I found some info online about a type 0x07 discovery packet and 0x08 response from the receiver card.  I have FPP working where it can send the discovery and use the response to determine what firmware is installed so it can send either one or two 0x01 packets since sending one works fine for older firmware while newer firmware needs both.  I am also sending the 0x01 'display frame' packet after the row data 0x55 packets are sent.

I need to rework some of the discovery code to make it non-blocking, as well as the code I added to send 0x01 after the 0x55 packets, but the concept worked as expected and the same code can drive both new and old firmware when not used together.  Sending from LEDVision works fine with dual 0x01 packets for both old and new firmware, so I think the flicker I see on old firmware when sending dual 0x01 is a timing issue so I am still playing around with that as well.   With the patched FPP, I do not see flicker when driving newer 13.x firmware, so I think this is possibly caused by using LEDVision (or Windows) to send the packets.

**Comment by mjunek** [comment]
Sounds like you're making good progress there @cpinkham  - fantastic work.

> With the patched FPP, I do not see flicker when driving newer 13.x firmware, so I think this is possibly caused by using LEDVision (or Windows) to send the packets.

I did notice in my packet captures that LEDVision was doubling every packet causing the flicker. This was not evident in the sender card. Seems a common issue as noted in Greg Macarees video linked [in post 2 above](https://github.com/FalconChristmas/fpp/issues/1849#issuecomment-2157157690)

> I have been testing with 3.x and 13.x firmware, and need to test with a third card I have.
If you've got it set up as a branch here, I can pull down the code and test it against a v6.0 board and v8.2 board, with a couple of different firmware versions as well.

I've also got a pair of 5A-75E 16 port boards driving my main panels that I can also use for testing (which are some interesting panels in themselves)

**Comment by cpinkham** [comment]
Once I rework the hacks I have in there right now, I will push some code to git.  I have some places where I messed with some variables, and made multiple calls to sendmmsg() with some sprinkled some sleeps to simulate sending the 0x55 and 0x01 at different times and have some blocking recvfrom() to receive the discovery replies.  Ideally we will send the 0x55 when we prep the next frame of output in PrepData() and when it is time to display we only need to send the 0x01 packet to display the frame data we previously sent.  Right now we send the 0x01 and immediately send the row data for the next frame so we may actually be behind one frame compared to the rest of the lights, although that is just a theory.  I have seen some other code on the net that sends the 0x55 first then the 0x01, so that seems to support the idea that the 0x01 is 'display frame'.

**Comment by dkulp** [comment]
Almost wonder if sending the row data should be done in "PrepData" and during SendData, we just send the 0x01 to display it.

**Comment by cpinkham** [comment]
> Almost wonder if sending the row data should be done in "PrepData" and during SendData, we just send the 0x01 to display it.

I think that's what I said, just in too many words. :)  Right now my test code is just faking it with some sleeps while I tested some things, but I want to split it up this way before committing anything.  I also want to do some more testing on the brightness field and whether/when we need the brightness packet.

**Comment by cpinkham** [comment]
I have the code cleaned up and will commit soon.  Right now it still sends one 0x01 for older firmware and two 0x01 for newer firmware as I haven't been able to get anything working yet that will work for both old and new.  The only issue with that is you can't chain old/new FW cards together and have both work at the same time.  I had it working somewhat, but the panel on the older firmware flickered and was much dimmer than the panel on the newer firmware.

I redid when packets are sent so the brightness and pixel data packets are sent in PrepData() with only the 0x01 sync packet sent in SendData().  I have enabled the Brightness setting in the LED Panel UI for ColorLight cards and have a lua wireshark dissector that I will include in the docs directory.  The lua script is based slightly on the one that @AlecDusheck posted above, but with a lot more parsing.  To test, I have been running wireshark passing the script with "-X lua_script:/path/to/the/ColorLight_Wireshark.lua" to enable dissecting a pcap with ColorLight packets.

I have been testing with v6.x and v8.x 5A-75B receivers running v2.0, v3.60, and v13.13 firmware.  For reference, I also grabbed a bunch of packet captures from when the config is pushed when the 'send' button is pressed in LEDVision and also when firmware is uploaded/downloaded.

**Comment by cpinkham** [comment]
The patch to support v13.x firmware was committed in d49ad41ed8.  Closing ticket.  When I have more time, I may look more into seeing if the code can support both old and new versions at the same time, but for now it is old or new but not both chained together.

**Comment by cpinkham** [comment]
@Indigogyre could you get another packet capture from the sender card after setting up a receiver with v13.x firmware and confirming the sender can talk to it correctly?  It only needs to be 5 seconds long if the sender is sending data.  I just need to see a few frames of data being sent to the receiver to compare to my other captures.
